---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doomsdayrs.
--- DateTime: 1/24/20 12:19 PM
---

object = nil

function test()
    print("Testing from wrap")
    return object:test(object)
end