---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doomsdayrs.
--- DateTime: 1/23/20 5:23 PM
---

local Madara = Require("Madara").Madara:new(nil, "A Site", "url", "lang", "date")

print(Madara.name)