---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doomsdayrs.
--- DateTime: 1/23/20 5:23 PM
---

local Library = Require("Madara")

local VipNovel = Library.Madara:new(nil, "https://vipnovel.com/", 395, "", "VipNovel", "en", "MMMM yy dd")

function VipNovel:test()
    print("This is VipNovel")
end

function get()
    return VipNovel
end